-- AlterTable
ALTER TABLE "InvoiceProduct" ALTER COLUMN "includesVat" DROP DEFAULT,
ALTER COLUMN "price" DROP DEFAULT,
ALTER COLUMN "currency" DROP DEFAULT,
ALTER COLUMN "vat" DROP DEFAULT,
ALTER COLUMN "unit" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "includesVat" DROP DEFAULT,
ALTER COLUMN "price" DROP DEFAULT,
ALTER COLUMN "currency" DROP DEFAULT,
ALTER COLUMN "vat" DROP DEFAULT,
ALTER COLUMN "unit" DROP DEFAULT;
